# Generated by Django 3.0.4 on 2021-01-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Favorite entry', 'verbose_name_plural': 'Favorite entries'},
        ),
    ]
