# Generated by Django 3.0.4 on 2021-01-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_auto_20210128_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Favorites entry', 'verbose_name_plural': 'Favorites entries'},
        ),
    ]
